### ISSUE TITLE
Prooftree della big-step

### ISSUE THREAD

**Issue by ghost** [UNIPR-Semantica/SemanticaUniPR#2]
Volevo sottolineare un problema nell'uso del prooftree per le dimostrazioni ad albero. Fin quando necessitiamo di una sola barra orizzontale per la regola non c'è nessun problema ma nelle dimostrazioni, se devo scrivere la side condition a destra e il nome della regola sulla sinistra, quest'ultimo non viene scritto a fianco della barra orizzontale ma allo stesso livello delle premesse.

**Comment by RobertoBagnara** [comment]
On 01/09/15 16:19, Amerigo Mancino wrote:

> Volevo sottolineare un problema nell'uso del prooftree per le dimostrazioni ad albero. Fin quando necessitiamo di una sola barra orizzontale per la regola non c'è nessun problema ma nelle dimostrazioni, se devo scrivere la side condition a destra e il nome della regola sulla sinistra, quest'ultimo non viene scritto a fianco della barra orizzontale ma allo stesso livello delle premesse.

Davvero strano.  A che pagina succede questa cosa?

## 

```
 Prof. Roberto Bagnara
```

Applied Formal Methods Laboratory - University of Parma, Italy
mailto:bagnara@cs.unipr.it
                              BUGSENG srl - http://bugseng.com
                              mailto:roberto.bagnara@bugseng.com

**Comment by ghost** [comment]
Dato che il risultato non era piacevole, per il momento non l'avevo inserito. Ora ho appena committato un caso in cui si avverte questo problema. Può vederlo a pagina 22.

**Comment by RobertoBagnara** [comment]
On 01/10/15 11:31, Amerigo Mancino wrote:

> Dato che il risultato non era piacevole, per il momento non l'avevo inserito. Ora ho appena committato un caso in cui si avverte questo problema. Può vederlo a pagina 22.

Ho visto.  Direi che non c'e` soluzione: rinunciamo a mettere i nomi
delle regole negli alberi (ma continuiamo a metterli nelle singole
regole).

## 

```
 Prof. Roberto Bagnara
```

Applied Formal Methods Laboratory - University of Parma, Italy
mailto:bagnara@cs.unipr.it
                              BUGSENG srl - http://bugseng.com
                              mailto:roberto.bagnara@bugseng.com

**Comment by ghost** [comment]
D'accordo, aggiorno appena posso allora.
