### ISSUE TITLE
Macro

### ISSUE THREAD

**Issue by Orion2193** [UNIPR-Semantica/SemanticaUniPR#3]
Volevo chiedere se potevamo metterci d'accordo sulla notazione da usare per la sostituzione (per capirci s[x->n] o s[x/n]) in modo da poter utilizzare tutti la stessa macro, e nel primo caso se va bene per tutti se usassimo la freccia \mapsto come ha consigliato il prof.

Altro avviso è che sto per inserire la macro \pts per spaziare verticalmente (specialmente comodo per non far venire i vari prooftree appiccicati) e per ora lo imposto a \[12pt]

**Comment by Orion2193** [comment]
Volevo inoltre proporre di modificare le macro di \lub \glb \max e \min in modo che dopo la parola lub ci sia uno spazio in modo da avere lub T invece che lubT

**Comment by RobertoBagnara** [comment]
On 01/09/15 22:21, Vale-Blast wrote:

> Volevo chiedere se potevamo metterci d'accordo sulla notazione da
> usare per la sostituzione (per capirci s[x->n] o s[x/n]) in modo da
> poter utilizzare tutti la stessa macro, e nel primo caso se va bene
> per tutti se usassimo la freccia \mapsto come ha consigliato il
> prof.

La mia proposta e` usare [x \mapsto n](introducendo una macro all'uopo)
per la modifica puntuale dello store (e operazioni simili), e usare la macro
\subst per la sostituzione, la quale genera [n/x] (notate bene: nella notazione
per gli store viene scritto prima x e poi n, viceversa in quella per
la sostituzione.

> Altro avviso è che sto per inserire la macro \pts per spaziare verticalmente (specialmente comodo per non far venire i vari prooftree appiccicati) e per ora lo imposto a [12pt]

OK.

## 

```
 Prof. Roberto Bagnara
```

Applied Formal Methods Laboratory - University of Parma, Italy
mailto:bagnara@cs.unipr.it
                              BUGSENG srl - http://bugseng.com
                              mailto:roberto.bagnara@bugseng.com

**Comment by RobertoBagnara** [comment]
On 01/10/15 10:06, Vale-Blast wrote:

> Volevo inoltre proporre di modificare le macro di \lub \glb \max e \min in modo che dopo la parola lub ci sia uno spazio in modo da avere lub T invece che lubT

Bocciata.

## 

```
 Prof. Roberto Bagnara
```

Applied Formal Methods Laboratory - University of Parma, Italy
mailto:bagnara@cs.unipr.it
                              BUGSENG srl - http://bugseng.com
                              mailto:roberto.bagnara@bugseng.com

**Comment by Orion2193** [comment]
Ok, ho introdotto la macro \assign per l'assegnamento usando la freccia \mapsto
