### ISSUE TITLE
Math Mode

### ISSUE THREAD

**Issue by Orion2193** [UNIPR-Semantica/SemanticaUniPR#4]
Mentre sono in modo matematico mi sono accorto che latex non cambia pagina in automatico ma fa semplicemente "sparire" il testo di troppo lasciando dello spazio bianco nella pagina seguente. Ho provato sia con \allowdisplaybreaks che con \pagebreak e simili ma non riesco a separare quel testo... qualcuno ha avuto un problema simile al mio?

**Comment by RobertoBagnara** [comment]
On 01/12/15 10:46, Vale-Blast wrote:

> Mentre sono in modo matematico mi sono accorto che latex non cambia pagina in automatico ma fa semplicemente "sparire" il testo di troppo lasciando dello spazio bianco nella pagina seguente. Ho provato sia con \allowdisplaybreaks che con \pagebreak e simili ma non riesco a separare quel testo... qualcuno ha avuto un problema simile al mio?

Che pagina?

## 

Prof. Roberto Bagnara
Applied Formal Methods Laboratory
Department of Mathematics and Computer Science, University of Parma, Italy
http://www.cs.unipr.it/~bagnara/
mailto:bagnara@cs.unipr.it

**Comment by Orion2193** [comment]
Non ho il PC vicino perciò non so la pagina ma è nella semantica small-step del linguaggio while

--- Messaggio originale ---

Da: "RobertoBagnara" notifications@github.com
Inviata: 12 Gennaio 2015 16:16
A: "DrSchottky/SemanticaUniPR" SemanticaUniPR@noreply.github.com
Cc: "Vale-Blast" valentino2193@hotmail.it
Oggetto: Re: [SemanticaUniPR] Math Mode (#4)

On 01/12/15 10:46, Vale-Blast wrote:

> Mentre sono in modo matematico mi sono accorto che latex non cambia pagina in automatico ma fa semplicemente "sparire" il testo di troppo lasciando dello spazio bianco nella pagina seguente. Ho provato sia con \allowdisplaybreaks che con \pagebreak e simili ma non riesco a separare quel testo... qualcuno ha avuto un problema simile al mio?

Che pagina?

## 

Prof. Roberto Bagnara
Applied Formal Methods Laboratory
Department of Mathematics and Computer Science, University of Parma, Italy
http://www.cs.unipr.it/~bagnara/
mailto:bagnara@cs.unipr.it

---

**Comment by Orion2193** [comment]
È circa a pagina 29, dove ci sono i vari prooftree di tutti i comandi nel capitolo sulla semantica small-step

**Comment by RobertoBagnara** [comment]
Buongiorno.

On 01/13/15 08:49, Vale-Blast wrote:

> È circa a pagina 29, dove ci sono i vari prooftree di tutti i comandi nel capitolo sulla semantica small-step

Non si deve fare un gather così lungo.

1) Quella parte va divisa in sottosezioni non numerate
   (subsection*) una per ogni costrutto.
2) Non vanno mescolate le espressioni con i comandi
   (ora si inizia con skip e poi si va avanti con le
   espressioni).
3) Non stai usando le macro giuste per scrivere la
   sintassi (vedi capitolo while.tex), ad esempio
   devi scrivere \kw{skip}.
4) I tab non vanno usati: indentazione 2 spazi.
5) Non ci sono vantaggi a considerare la versione
   senza effetti collaterali.  Meglio presentare
   direttamente la versione con possibili effetti
   collaterali ed aggiungere una spiegazione dei
   vantaggi.

## 

Prof. Roberto Bagnara
Applied Formal Methods Laboratory
Department of Mathematics and Computer Science, University of Parma, Italy
http://www.cs.unipr.it/~bagnara/
mailto:bagnara@cs.unipr.it

**Comment by Orion2193** [comment]
Ma devo togliere la parte senza effetti collaterali dalla small-step o dall denotazionale?

**Comment by RobertoBagnara** [comment]
On 14/01/2015 11:14, Vale-Blast wrote:

> Ma devo togliere la parte senza effetti collaterali dalla small-step o dall denotazionale?

Huh?  Sarà meglio che ne parliamo a voce, tra poco.

## 

Prof. Roberto Bagnara
Applied Formal Methods Laboratory
Department of Mathematics, University of Parma, Italy
http://www.cs.unipr.it/~bagnara/
mailto:bagnara@cs.unipr.it
